spring:
  application:
    name: parkinglot
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        boot:
          allow_jdbc_metadata_access: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/parkinglot
    username: postgres
    password: postgres
    hikari:
      poolName: Hikari
      auto-commit: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: powerm4f13@gmail.com
    password: ssssssssssssssssssss
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  docker:
    compose:
      enabled: true
      file: src/main/docker/services.yml
      lifecycle-management: start_only
      start:
        skip: if_running
  messages:
    basename: i18n/messages

server:
  port: 8080

application:
  security:
    content-security-policy: "default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:"
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        # As this is the PRODUCTION configuration, you MUST change the default key, and store it securely:
        # - In the Consul configserver
        # - In a separate `application-prod.yml` file, in the same folder as your executable JAR file
        base64-secret: YTVjNzIwZjJiYzQ3MDBhYzc3MjY2OGFmOGE2MjkwN2U4NDNlMmFmOWY2YmI2YWNkYWZkZjY0OWFhMjdkMzAyZTVjNDFiOWVjMzZjYmQ3YWNiNDc5OWI5Nzk1Nzc3MDQwMjgyYWI3ZDc4NjFlZjg4OGNhYzQyNjZkMzIxMzI2NzA=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail:
    from: test@localhost
    base-url: http://127.0.0.1:8080

springdoc:
  swagger-ui:
    path: /swagger-ui/api-doc.html
